### ISSUE TITLE
云函数

### ISSUE THREAD

**Issue by CreamK** [shylocks/Loon#1]
大佬，为什么我部署在云函数阅读文章一会好一会不行，不行的时候说这篇文章阅读时间太长

**Comment by shylocks** [comment]
具体报错提示？发下log

**Comment by CreamK** [comment]
[云函数每天前几次就OK的，之后看文章这部分就随缘了，有时候看一片有时候不看，基本上运行一次最多一篇
![Uploading IMG_20210103_103535.jpg…]()

**Comment by CreamK** [comment]
![Uploading IMG_20210103_103535.jpg…]()

**Comment by CreamK** [comment]
![IMG_20210103_103535](https://user-images.githubusercontent.com/51256470/103470674-02b60c00-4db0-11eb-80c9-aa85e2575234.jpg)

**Comment by CreamK** [comment]
我发现大致问题是cookie中某个参数的问题，我换了一个参数就又可以看几篇，过一会又说读了很久换一篇，大佬能优化一下吗

**Comment by shylocks** [comment]
安卓的ck暂时无解

**Comment by CreamK** [comment]
> 安卓的ck暂时无解

我用平板抓的

**Comment by CreamK** [comment]
现在的解决方案是放三个一个账号的cookie，一次运行900秒如果正常第一个账号会执行不完然后断开，等一会继续执行，运行错误的话第一个很快运行完而且没有超过900秒然后运行第二个cookie
