### ISSUE TITLE
工业品消除助力提示出错

### ISSUE THREAD

**Issue by hunter99881** [shylocks/Loon#12]
消除报错:,"errMsg":"right is aab1a5c2f1b0********85

**Comment by Mirasc** [comment]
任务完成失败，错误信息：{"code":4121,"errMsg":"active_task_no_achive","serverTime":1610959366197}
请问大佬这种错误是怎么回事？ @shylocks

**Comment by hunter99881** [comment]
> 任务完成失败，错误信息：{"code":4121,"errMsg":"active_task_no_achive","serverTime":1610959366197}
> 请问大佬这种错误是怎么回事？ @shylocks

助力没有完成,当然没有助力奖励了,你那边能成功助力?

**Comment by Mirasc** [comment]
哦哦  原来是助力任务   我懂了   谢谢！ @shylocks

**Comment by shylocks** [comment]
fixed in 77a51c1a7e07cbf4538531006c1d934ab831dfb7
