### ISSUE TITLE
消消乐跟工业好像缺少体力判断跳出

### ISSUE THREAD

**Issue by Mark-1215** [shylocks/Loon#13]
消消乐跟工业好像缺少体力判断跳出，经常运行一段时间出现大量关卡开启失败，体力不足
[jd_xxl.js   info][2021-01-18 22:00:32.889]: 关卡开启失败，体力不足
[jd_xxl.js   info][2021-01-18 22:00:33.016]: 关卡开启失败，体力不足
[jd_xxl.js   info][2021-01-18 22:00:33.132]: 关卡开启失败，体力不足
[jd_xxl.js   info][2021-01-18 22:00:33.245]: 关卡开启失败，体力不足
[jd_xxl.js   info][2021-01-18 22:00:33.360]: 关卡开启失败，体力不足
[jd_xxl.js   info][2021-01-18 22:00:33.475]: 关卡开启失败，体力不足
[jd_xxl.js   info][2021-01-18 22:00:33.587]: 关卡开启失败，体力不足
[jd_xxl.js   info][2021-01-18 22:00:33.707]: 关卡开启失败，体力不足
[jd_xxl.js   info][2021-01-18 22:00:33.828]: 关卡开启失败，体力不足
[jd_xxl.js   info][2021-01-18 22:00:33.961]: 关卡开启失败，体力不足
[jd_xxl.js   info][2021-01-18 22:00:34.088]: 关卡开启失败，体力不足
[jd_xxl.js   info][2021-01-18 22:00:34.204]: 关卡开启失败，体力不足

**Comment by shylocks** [comment]
fixed in 77a51c1a7e07cbf4538531006c1d934ab831dfb7
