### ISSUE TITLE
xxl部分关卡只有两星，希望有机会可以把这些没有三星的关卡改为三星

### ISSUE THREAD

**Issue by EchoChan314** [shylocks/Loon#16]
因为之前玩过xxl的部分关卡，有些关卡只有两星甚至一星。发现用脚本后是跳过这些已经玩过的关卡。希望作者大大有机会把那些没有三星的关卡改为三星。
另外，每日任务的三颗星星貌似不会自动领取，不过这测试一次，可能不准。

**Comment by shylocks** [comment]
入会无法自动领取

**Comment by ilaotan** [comment]
同意，能不能指定level ，如果指定了，从指定level开始打。。。

**Comment by shylocks** [comment]
fix in 6402b9f
