### ISSUE TITLE
jd_xxl_gh 输出log有些奇怪

### ISSUE THREAD

**Issue by EchoChan314** [shylocks/Loon#19]
![photo_2021-01-19_23-25-19.jpg](https://i.loli.net/2021/01/19/4dOglcs8D2tGEeN.jpg)
![photo_2021-01-19_23-25-23.jpg](https://i.loli.net/2021/01/19/Dw4UJBGXNl3QM8H.jpg)
体力和通过数不一样，只有星星数是一样的。任务也已经完成了。

**Comment by GoToBoy** [comment]
好像加密了
![image](https://user-images.githubusercontent.com/2384105/105106949-e923fc80-5af1-11eb-8ffd-eefd383e52d6.png)
![image](https://user-images.githubusercontent.com/2384105/105106953-ede8b080-5af1-11eb-8a09-76f229c8df40.png)
![image](https://user-images.githubusercontent.com/2384105/105107010-0ce74280-5af2-11eb-95cc-ff741aee1df2.png)
