### ISSUE TITLE
个护消消乐跑不起来

### ISSUE THREAD

**Issue by sofs2005** [shylocks/Loon#20]
每次都说体力不够，实际是够的

**Comment by sofs2005** [comment]
刚刚发现工业品消消乐报api请求失败，不知是个别问题还是狗东改代码了

**Comment by sofs2005** [comment]
> 刚刚发现工业品消消乐报api请求失败，不知是个别问题还是狗东改代码了

工业品这个应该还是好用的，虽然报api但还是能跑起来

**Comment by shylocks** [comment]
已黑号，勿念
