### ISSUE TITLE
我这个xxl遇到bug了么，没法升级了。

### ISSUE THREAD

**Issue by ilaotan** [shylocks/Loon#27]
******开始【京东账号3】xxxx*********

由于您第3个京东账号未提供shareCode,将采纳本脚本自带的助力码

第3个京东账号将要助力的好友["840266","2585219","2586018","1556311","2583822","2585256"]
您的好友助力码为：2811558
当前星星：234
当前体力：23
去领取好友助力任务
暂无每日挑战任务
去助力好友840266
去助力好友2585219
去助力好友2586018
去助力好友1556311
去助力好友2583822
去助力好友2585256
您的好友助力码为：2811558
当前星星：234
当前体力：23
去领取好友助力任务
暂无每日挑战任务

🔔东东爱消除, 结束! 🕛 52.697 秒

**Comment by Mark-1215** [comment]
同样问题，脚本出错了。

**Comment by kissyouhunter** [comment]
更新后
无法运行了

**Comment by Mark-1215** [comment]
更新后这样了
TypeError: Cannot read property 'platform' of undefined
[jd_xxl.js   info][2021-01-21 03:00:00.764]: ❗️东东爱消除, 错误!
TypeError: data.tasks is not iterable
[jd_xxl.js   info][2021-01-21 03:00:00.886]: 关卡开启失败，错误信息：{"code":-1,"errMsg":"param [token required and type limit string]","__line__":"[node_modules/mx-webserve/src/webHandle.ts:79:23]"}
[jd_xxl.js   info][2021-01-21 03:00:00.888]: 当前关卡：NaN
[jd_xxl.js   info][2021-01-21 03:00:00.890]: ❌ 东东爱消除, 失败! 原因: TypeError: Cannot read property 'length' of undefined!
[jd_xxl.js   info][2021-01-21 03:00:00.892]: 🔔东东爱消除, 结束! 🕛 0.797 秒

**Comment by Mark-1215** [comment]
经过重新抓包测试，发现是游戏系统的原因，返回系统异常，请作者不要先检查原因了，先等系统恢复再做测试，可能错误代码跟跟脚本无关。

**Comment by shylocks** [comment]
已黑号，勿念
