### ISSUE TITLE
gyec和xxl两个脚本运行错误

### ISSUE THREAD

**Issue by 2607627233** [shylocks/Loon#29]
![Screenshot_20210121-104833](https://user-images.githubusercontent.com/43110396/105273430-41ccc580-5bd6-11eb-9e6a-214ff1cf408a.png)
![Screenshot_20210121-104812](https://user-images.githubusercontent.com/43110396/105273435-442f1f80-5bd6-11eb-91be-140bcfbd8ceb.png)
这两个脚本是一次性的吗 ，20号还能正常运行 21号就都运行错误了。

**Comment by EchoChan314** [comment]
京东的问题，你app也进不去

**Comment by iyzgit** [comment]
我的也一样，app也无法进去，可是别人的就可以。好像是黑号了:(  大佬有方法能绕过去吗？

**Comment by shylocks** [comment]
已黑号，勿念
