### ISSUE TITLE
我运行出错 “视频阅读失败，错误信息：参数为空”

### ISSUE THREAD

**Issue by cr15g** [shylocks/Loon#4]
用docker运行，提示：视频阅读失败，错误信息：参数为空
这个是什么原因造成的，用手机QX正常。

**Comment by nekomiao123** [comment]
应该是docker网络设置的问题 我物理机跑没事 docker也遇到了这个问题 试过改成host好像也不行 暂时拿物理机跑吧

**Comment by shylocks** [comment]
部分ip获取不到广告，所以没有视频，暂时无解

**Comment by cr15g** [comment]
应该不是ip获取不到广告，我用相同的ip，手机可以，不知道是哪里有问题

**Comment by tianya908** [comment]
> 应该是docker网络设置的问题 我物理机跑没事 docker也遇到了这个问题 试过改成host好像也不行 暂时拿物理机跑吧

请问物理机运行需要怎么修改参数  求指导
我用githu actions运行 报下面的错误
视频阅读失败，错误信息：
去看视频：79641860
文章剩余观看次数：150，视频剩余观看次数：50

**Comment by shylocks** [comment]
> > 应该是docker网络设置的问题 我物理机跑没事 docker也遇到了这个问题 试过改成host好像也不行 暂时拿物理机跑吧
> 
> 请问物理机运行需要怎么修改参数 求指导
> 我用githu actions运行 报下面的错误
> 视频阅读失败，错误信息：
> 去看视频：79641860
> 文章剩余观看次数：150，视频剩余观看次数：50

ac无法运行
