### ISSUE TITLE
觉得可用的话就放icon里吧👀一点微小的工作

### ISSUE THREAD

**Issue by yogayyy** [shylocks/Loon#8]
![jd_mh](https://user-images.githubusercontent.com/50315632/104743589-d2df0f00-5786-11eb-942b-f9eaf33ebe07.png)
![jd_bj](https://user-images.githubusercontent.com/50315632/104743599-d6729600-5786-11eb-8b20-a95af3fdf307.png)
![6D8DA2BF-30E0-40A9-AA8F-783BF9AEC482](https://user-images.githubusercontent.com/50315632/104744056-61ec2700-5787-11eb-9f66-706766987856.jpeg)

**Comment by yogayyy** [comment]
jd_mh
jd_bj
jd_wechat_sign

**Comment by shylocks** [comment]
收到，感谢！

**Comment by yogayyy** [comment]
> 收到，感谢！

@shylocks 大佬，修改了部分图标，目前除了神券驾到都补了图标，工业消消乐也做了，如果有boxjs对应的图标需求，也做了对应的mini版本，缺的以后再补吧~


#超级直播间红包雨
30,31 20-23/1 15 1 * https://raw.githubusercontent.com/shylocks/Loon/main/jd_live_redrain.js, tag=超级直播间红包雨, img-url=https://raw.githubusercontent.com/yogayyy/Scripts/main/Icon/shylock/jd_live_redrain.png,  enabled=true
============================
hostname = wq.jd.com
[rewrite_local]
https:\/\/wq\.jd\.com\/bases\/jssdk\/GetWxJsApiSign url script-request-header https://raw.githubusercontent.com/shylocks/Loon/main/jd_wechat_sign.js
[task_local]
#京东粉丝专享
1 7 * * * https://raw.githubusercontent.com/shylocks/Loon/main/jd_wechat_sign.js, tag=京东粉丝专享, img-url=https://raw.githubusercontent.com/yogayyy/Scripts/main/Icon/shylock/jd_wechat_sign.png,  enabled=true
============================
#京东秒秒币
1 7 * * * https://raw.githubusercontent.com/shylocks/Loon/main/jd_ms.js, tag=京东秒秒币, img-url=https://raw.githubusercontent.com/yogayyy/Scripts/main/Icon/shylock/jd_ms.png, enabled=true
============================
#宝洁美发屋
1 8,9 14-31/1 1 * https://raw.githubusercontent.com/shylocks/Loon/main/jd_bj.js, tag=宝洁美发屋, img-url=https://raw.githubusercontent.com/yogayyy/Scripts/main/Icon/shylock/jd_bj.png,  enabled=true
============================
#盲盒抽京豆
1 7 * * * https://raw.githubusercontent.com/shylocks/Loon/main/jd_mh.js, tag=盲盒抽京豆, img-url=https://raw.githubusercontent.com/yogayyy/Scripts/main/Icon/shylock/jd_mh.png,  enabled=true
============================、
工业消消乐（蓄势待发）
https://raw.githubusercontent.com/yogayyy/Scripts/main/Icon/shylock/jd_gyxxl.png
https://raw.githubusercontent.com/yogayyy/Scripts/main/Mini/shylocks/jd_gyxxl_mini.png

**Comment by shylocks** [comment]
有空可以做个京东粉丝专享的boxjs版本
