### ISSUE TITLE
宝洁美发屋-错误

### ISSUE THREAD

**Issue by Mark-1215** [shylocks/Loon#9]
[jd_bj-...js info][2021-01-16 23:04:59.069]: 京东服务器访问数据为空，请检查自身设备网络情况
[jd_bj-...js info][2021-01-16 23:04:59.068]: SyntaxError: Unexpected end of JSON input
[jd_bj-...js info][2021-01-16 23:04:58.974]: 京东服务器访问数据为空，请检查自身设备网络情况
[jd_bj-...js info][2021-01-16 23:04:58.973]: SyntaxError: Unexpected end of JSON input
[jd_bj-...js info][2021-01-16 23:04:58.657]: 京东服务器访问数据为空，请检查自身设备网络情况
[jd_bj-...js info][2021-01-16 23:04:58.657]: SyntaxError: Unexpected end of JSON input
[jd_bj-...js info][2021-01-16 23:04:58.557]: 京东服务器访问数据为空，请检查自身设备网络情况
[jd_bj-...js info][2021-01-16 23:04:58.556]: SyntaxError: Unexpected end of JSON input
[jd_bj-...js info][2021-01-16 23:04:58.462]: 京东服务器访问数据为空，请检查自身设备网络情况
[jd_bj-...js info][2021-01-16 23:04:58.461]: SyntaxError: Unexpected end of JSON input
[jd_bj-...js info][2021-01-16 23:04:58.365]: ❗️宝洁美发屋, 错误!
TypeError: Cannot read property 'split' of undefined

**Comment by shylocks** [comment]
京东服务器访问数据为空京东服务器访问数据为空京东服务器访问数据为空

**Comment by Mark-1215** [comment]
其他脚本都正常。。。不知道就这个错了。
